from __future__ import annotations

import copy
import json
import textwrap
from pathlib import Path
from typing import Any

from .artifacts import (
    build_offline_artifact_manifests,
    ensure_output_dir,
    write_json,
    write_text,
)
from .config_emit import emit_parameter_config
from .python_ttnn import (
    build_codegen_config,
    render_python_ttnn_model,
)
from ..semantic.dump import graph_json_dict
from ..semantic.graph import LlamaModelGraph
from ..templates.diff import expand_final_templates, expand_layer_templates


PROGRAM_ARTIFACTS = (
    "model.py",
    "config.json",
    "semantic_graph.json",
    "execution_plan.json",
    "weights_manifest.json",
    "run_decode.py",
    "README.md",
)


def write_decode_program_bundle(
    *,
    graph: LlamaModelGraph,
    plan: dict[str, Any],
    template_config: dict[str, Any],
    model_path: str | Path,
    out_dir: str | Path,
) -> dict[str, Path]:
    root = ensure_output_dir(out_dir)
    paths = {name: root / name for name in PROGRAM_ARTIFACTS}
    parameter_config = emit_parameter_config(
        graph,
        recipe=template_config["dtype_recipe"],
        lm_head_split_count=int(template_config["lm_head_split_count"]),
    )
    weights_manifest = build_offline_artifact_manifests(
        model_path,
        graph,
        parameter_config,
    )["weights_manifest.json"]

    write_text(paths["model.py"], render_python_ttnn_model(plan))
    write_json(paths["config.json"], build_codegen_config(plan))
    write_json(paths["semantic_graph.json"], graph_json_dict(graph))
    write_json(paths["execution_plan.json"], copy.deepcopy(plan))
    write_json(paths["weights_manifest.json"], weights_manifest)
    write_text(paths["run_decode.py"], render_run_decode_py(plan))
    write_text(paths["README.md"], render_program_readme(plan))
    return paths


def render_run_decode_py(plan: dict[str, Any]) -> str:
    dry_run_payload = build_decode_dry_run_payload(plan)
    script = '''# Auto-generated by Buddy-TTNN Direct.
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


DRY_RUN_PAYLOAD = __DRY_RUN_PAYLOAD__
TOOL_ROOT = Path(__TOOL_ROOT__)


def _program_dir():
    return Path(__file__).resolve().parent


def _ensure_repo_import_path():
    candidates = []
    env_root = os.environ.get("BUDDY_MLIR_ROOT")
    if env_root:
        candidates.append(Path(env_root))
    candidates.extend([Path.cwd(), TOOL_ROOT, _program_dir()])
    candidates.extend(_program_dir().parents)
    for candidate in candidates:
        if (candidate / "models" / "llama_ttnn_direct").is_dir():
            path = str(candidate)
            if path not in sys.path:
                sys.path.insert(0, path)
            return


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Run or inspect a Buddy-TTNN Direct decode bundle."
    )
    parser.add_argument(
        "--mode",
        choices=("inspect", "smoke", "profile", "validate-real"),
        default="inspect",
        help=(
            "inspect prints the planned op sequence; smoke/profile run the "
            "generated decode_step path; validate-real chains real-weight "
            "materialize/smoke/profile/autotune gates."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "For inspect, print the op sequence. For smoke/profile/validate, "
            "write reports without opening a TTNN device."
        ),
    )
    parser.add_argument("--model-path", type=Path, default=None)
    parser.add_argument("--layers", type=int, default=1)
    parser.add_argument("--batch-size", type=int, default=None)
    parser.add_argument("--cache-len", type=int, default=None)
    parser.add_argument("--device", default="p150a")
    parser.add_argument("--device-id", type=int, default=0)
    parser.add_argument(
        "--dtype-seed",
        choices=("bf16", "fp32"),
        default="bf16",
    )
    parser.add_argument("--trace", action="store_true")
    parser.add_argument("--trace-iterations", type=int, default=1)
    parser.add_argument("--metric", default="latency_ms")
    parser.add_argument("--decode-step-search-space", type=Path, default=None)
    parser.add_argument("--skip-autotune", action="store_true")
    parser.add_argument("--require-trace", action="store_true")
    parser.add_argument(
        "--min-tokens-per-second-per-user",
        type=float,
        default=None,
    )
    parser.add_argument(
        "--decode-shell-pcc-threshold",
        type=float,
        default=0.99,
    )
    parser.add_argument(
        "--require-decode-shell-numeric-reference",
        action="store_true",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Report path for smoke/profile modes.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Report directory for validate-real mode.",
    )
    args = parser.parse_args(argv)
    program_dir = _program_dir()

    if args.mode == "inspect":
        print(json.dumps(DRY_RUN_PAYLOAD, indent=2))
        return 0

    if args.mode == "smoke":
        _ensure_repo_import_path()
        from models.llama_ttnn_direct.buddy_ttnn_direct.smoke_single_layer_decode import (
            run_smoke_decode_step,
        )

        report_path = args.out or program_dir / "decode_step_smoke_report.json"
        report = run_smoke_decode_step(
            out=report_path,
            program_dir=program_dir,
            layers=args.layers,
            model_path=args.model_path,
            device=args.device,
            device_id=args.device_id,
            batch_size=args.batch_size,
            cache_len=args.cache_len,
            dtype_seed=args.dtype_seed,
            trace=args.trace,
            trace_iterations=args.trace_iterations,
            dry_run=args.dry_run,
        )
        print(json.dumps({"status": report["status"], "report": str(report_path)}, indent=2))
        return _report_exit_code(report)

    if args.mode == "profile":
        _ensure_repo_import_path()
        from models.llama_ttnn_direct.buddy_ttnn_direct.smoke_single_layer_decode import (
            profile_decode_step,
        )

        report_path = args.out or program_dir / "decode_step_profile_report.json"
        report = profile_decode_step(
            out=report_path,
            program_dir=program_dir,
            layers=args.layers,
            model_path=args.model_path,
            device=args.device,
            device_id=args.device_id,
            batch_size=args.batch_size,
            cache_len=args.cache_len,
            dtype_seed=args.dtype_seed,
            trace=args.trace,
            trace_iterations=args.trace_iterations,
            dry_run=args.dry_run,
        )
        print(json.dumps({"status": report["status"], "report": str(report_path)}, indent=2))
        return _report_exit_code(report)

    if args.model_path is None and not args.dry_run:
        raise SystemExit("--model-path is required for --mode validate-real")
    _ensure_repo_import_path()
    from models.llama_ttnn_direct.buddy_ttnn_direct.validation import (
        validate_real_decode,
    )

    out_dir = args.out_dir or program_dir / "real_decode_validation"
    report = validate_real_decode(
        program_dir=program_dir,
        model_path=args.model_path or program_dir,
        out_dir=out_dir,
        decode_step_search_space_path=args.decode_step_search_space,
        layers=args.layers,
        batch_size=args.batch_size,
        cache_len=args.cache_len,
        device=args.device,
        device_id=args.device_id,
        dtype_seed=args.dtype_seed,
        trace=args.trace,
        trace_iterations=args.trace_iterations,
        metric=args.metric,
        dry_run=args.dry_run,
        skip_autotune=args.skip_autotune,
        require_trace=args.require_trace,
        min_tokens_per_second_per_user=args.min_tokens_per_second_per_user,
        decode_shell_pcc_threshold=args.decode_shell_pcc_threshold,
        require_decode_shell_numeric_reference=(
            args.require_decode_shell_numeric_reference
        ),
    )
    report_path = out_dir / "real_decode_validation_report.json"
    print(json.dumps({"status": report["status"], "report": str(report_path)}, indent=2))
    return 0 if report["status"] in {"pass", "dry_run"} else 1


def _report_exit_code(report):
    if report.get("status") == "no_device":
        return 2
    if report.get("passed") or report.get("status") in {"dry_run", "profiled"}:
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
'''
    return script.replace(
        "__DRY_RUN_PAYLOAD__",
        json.dumps(dry_run_payload, indent=4),
    ).replace(
        "__TOOL_ROOT__",
        json.dumps(str(Path(__file__).resolve().parents[4])),
    )


def build_decode_dry_run_payload(plan: dict[str, Any]) -> dict[str, Any]:
    layers = [
        {
            "layer_id": layer["layer_id"],
            "ops": expand_layer_templates(layer["templates"]),
        }
        for layer in plan["layers"]
    ]
    return {
        "schema_version": 1,
        "mode": plan["mode"],
        "model_name": plan["model_name"],
        "num_layers": len(layers),
        "batch_size": plan["batch_size"],
        "seq_len": plan["seq_len"],
        "max_cache_len": plan["max_cache_len"],
        "layers": layers,
        "final_ops": expand_final_templates(plan["final"]),
    }


def render_program_readme(plan: dict[str, Any]) -> str:
    return textwrap.dedent(
        f"""
        # Buddy-TTNN Direct Decode Program

        This directory contains a generated Buddy-TTNN Direct decode bundle.
        It wires together semantic import, template planning, Python TTNN
        codegen, and offline weight metadata.

        Model: `{plan["model_name"]}`
        Layers: `{len(plan["layers"])}`
        Mode: `{plan["mode"]}`

        Generated files:

        ```text
        model.py
        config.json
        semantic_graph.json
        execution_plan.json
        weights_manifest.json
        run_decode.py
        README.md
        ```

        Inspect the decode op sequence with:

        ```bash
        python run_decode.py
        ```

        Run the generated decode smoke path from the bundle:

        ```bash
        python run_decode.py --mode smoke --layers 1 --device p150a \
          --out /tmp/decode_step_smoke_report.json
        ```

        Profile the generated decode path by section:

        ```bash
        python run_decode.py --mode profile --layers 1 --device p150a \
          --out /tmp/decode_step_profile_report.json
        ```

        Validate the real-weight path after providing a local HF model:

        ```bash
        python run_decode.py --mode validate-real \
          --model-path /path/to/Llama-3.1-8B-Instruct \
          --trace \
          --trace-iterations 10 \
          --require-trace \
          --min-tokens-per-second-per-user 1.0 \
          --decode-shell-pcc-threshold 0.99 \
          --require-decode-shell-numeric-reference \
          --out-dir /tmp/validate_ttnn_direct_real
        ```

        Add `--dry-run` to smoke/profile/validate-real to write report schemas
        without opening a TTNN device.
        """
    ).lstrip()
