from __future__ import annotations

import copy
import textwrap
from pathlib import Path
from typing import Any

from .artifacts import (
    build_offline_artifact_manifests,
    ensure_output_dir,
    write_json,
    write_text,
)
from .config_emit import emit_parameter_config
from .python_ttnn import build_codegen_config, render_python_ttnn_model
from ..compiler.official_config import (
    official_layer_dtype_overrides,
    official_weight_memory_overrides,
)
from ..semantic.dump import graph_json_dict
from ..semantic.graph import LlamaModelGraph


PROGRAM_ARTIFACTS = (
    "model.py",
    "config.json",
    "semantic_graph.json",
    "execution_plan.json",
    "weights_manifest.json",
    "run_decode.py",
    "README.md",
)


def write_decode_program_bundle(
    *,
    graph: LlamaModelGraph,
    plan: dict[str, Any],
    template_config: dict[str, Any],
    model_path: str | Path,
    out_dir: str | Path,
) -> dict[str, Path]:
    root = ensure_output_dir(out_dir)
    paths = {name: root / name for name in PROGRAM_ARTIFACTS}
    parameter_config = emit_parameter_config(
        graph,
        recipe=template_config["dtype_recipe"],
        lm_head_split_count=int(template_config["lm_head_split_count"]),
        layer_dtype_overrides=official_layer_dtype_overrides(
            template_config.get("official_config_profile"),
            dtype_recipe=str(template_config["dtype_recipe"]),
        ),
        weight_memory_overrides=official_weight_memory_overrides(
            template_config.get("official_config_profile"),
            lm_head_split_count=int(template_config["lm_head_split_count"]),
            vocab_size=graph.vocab_size,
        ),
    )
    weights_manifest = build_offline_artifact_manifests(
        model_path,
        graph,
        parameter_config,
    )["weights_manifest.json"]
    write_text(paths["model.py"], render_python_ttnn_model(plan))
    write_json(paths["config.json"], build_codegen_config(plan))
    write_json(paths["semantic_graph.json"], graph_json_dict(graph))
    write_json(paths["execution_plan.json"], copy.deepcopy(plan))
    write_json(paths["weights_manifest.json"], weights_manifest)
    write_text(paths["run_decode.py"], render_run_decode_py(plan))
    write_text(paths["README.md"], render_program_readme(plan))
    return paths


def render_run_decode_py(_plan: dict[str, Any]) -> str:
    script = r'''# Auto-generated by Buddy-TTNN Direct.
from __future__ import annotations

import os
import sys
from pathlib import Path


TOOL_ROOT = Path(__TOOL_ROOT__)
PRODUCT_COMMANDS = {
    "build",
    "generate",
    "profile",
    "validate",
    "inspect",
    "diagnose",
}
LEGACY_MODES = {
    "inspect": ("inspect",),
    "smoke": ("diagnose", "--stage", "decode-step"),
    "prefill-smoke": ("diagnose", "--stage", "prefill"),
    "profile": ("diagnose", "--stage", "decode-step"),
    "decode-loop": ("diagnose", "--stage", "decode-loop-legacy"),
    "generate": ("generate",),
    "profile-generate": ("profile", "--mode", "generate"),
    "validate-real": ("validate", "--suite", "device"),
}


def _program_dir() -> Path:
    return Path(__file__).resolve().parent


def _ensure_repo_import_path() -> None:
    candidates = []
    env_root = os.environ.get("BUDDY_MLIR_ROOT")
    if env_root:
        candidates.append(Path(env_root))
    candidates.extend([Path.cwd(), TOOL_ROOT, _program_dir()])
    candidates.extend(_program_dir().parents)
    for candidate in candidates:
        if (candidate / "models" / "llama_ttnn_direct").is_dir():
            path = str(candidate)
            if path not in sys.path:
                sys.path.insert(0, path)
            return


def _option_present(args: list[str], name: str) -> bool:
    return name in args or any(item.startswith(name + "=") for item in args)


def _insert_program_dir(command: str, args: list[str]) -> list[str]:
    if command == "build" or _option_present(args, "--program-dir"):
        return [command, *args]
    return [command, "--program-dir", str(_program_dir()), *args]


def _replace_option(args: list[str], old: str, new: str) -> list[str]:
    return [new if item == old else item for item in args]


def _translate(argv: list[str]) -> list[str] | None:
    raw = list(argv)
    if raw and raw[0] in PRODUCT_COMMANDS:
        return _insert_program_dir(raw[0], raw[1:])

    mode = "inspect"
    if "--mode" in raw:
        index = raw.index("--mode")
        if index + 1 >= len(raw):
            print("run_decode.py: --mode requires a value", file=sys.stderr)
            return None
        mode = raw[index + 1]
        raw[index:index + 2] = []
    if mode not in LEGACY_MODES:
        print(
            "run_decode.py: legacy mode is unavailable; use one of "
            "build, generate, profile, validate, inspect, diagnose",
            file=sys.stderr,
        )
        return None

    command = list(LEGACY_MODES[mode])
    if mode == "inspect":
        raw = [item for item in raw if item != "--dry-run"]
    if mode in {"generate", "profile-generate"}:
        raw = _replace_option(raw, "--decode-steps", "--max-new-tokens")
    if mode == "validate-real":
        if "--preflight-only" in raw:
            print(
                "run_decode.py: --preflight-only moved to the diagnostics API; "
                "use diagnose --stage performance-correctness",
                file=sys.stderr,
            )
            return None
        if "--dry-run" in raw:
            raw = [item for item in raw if item != "--dry-run"]
            command = ["validate", "--suite", "dryrun"]
        unsupported = {
            "--official-config",
            "--decode-step-search-space",
            "--performance-baselines",
            "--require-official-performance-parity",
            "--min-tokens-per-second-per-user",
            "--baseline-reference",
            "--min-baseline-ratio",
        }
        if any(item in unsupported for item in raw):
            print(
                "run_decode.py: validate-real legacy gates moved to "
                "diagnose stages; use diagnose --stage performance-correctness",
                file=sys.stderr,
            )
            return None

    if command[0] == "profile" and not _option_present(raw, "--out"):
        raw.extend(["--out", str(_program_dir() / "profile.json")])
    if command[0] == "diagnose" and not _option_present(raw, "--out"):
        raw.extend(["--out", str(_program_dir() / "diagnose.json")])
    if command[0] == "validate" and not _option_present(raw, "--out-dir"):
        raw.extend(["--out-dir", str(_program_dir() / "validation")])
    return _insert_program_dir(command[0], [*command[1:], *raw])


def main(argv: list[str] | None = None) -> int:
    _ensure_repo_import_path()
    from models.llama_ttnn_direct.buddy_ttnn_direct.cli import main as product_main

    forwarded = _translate(list(argv) if argv is not None else sys.argv[1:])
    if forwarded is None:
        return 2
    try:
        return int(product_main(forwarded))
    except SystemExit as exc:
        return int(exc.code or 0)


if __name__ == "__main__":
    raise SystemExit(main())
'''
    return script.replace(
        "__TOOL_ROOT__",
        repr(str(Path(__file__).resolve().parents[4])),
    )


def render_program_readme(plan: dict[str, Any]) -> str:
    return textwrap.dedent(
        f"""
        # Buddy-TTNN Direct Decode Program

        This generated bundle contains the model, execution plan, weight
        manifest, and a thin run_decode.py facade.

        Model: {plan["model_name"]}
        Layers: {len(plan["layers"])}
        Mode: {plan["mode"]}

        Generated files: model.py, config.json, semantic_graph.json,
        execution_plan.json, weights_manifest.json, run_decode.py, README.md.

        Use the facade from a runtime working directory:

            export BUDDY_MLIR_ROOT=/path/to/buddy-mlir
            python run_decode.py inspect
            python run_decode.py generate --model-path /path/to/model \\
              --prompt "Hello from TTNN Direct" --max-new-tokens 2
            python run_decode.py profile --mode decode-steady --dry-run \\
              --out profile.json
            python run_decode.py validate --suite dryrun --out-dir validation
            python run_decode.py diagnose --stage decode-step --dry-run \\
              --out diagnose.json

        The facade automatically supplies --program-dir. Historical mode names
        remain a small compatibility layer: smoke maps to diagnose decode-step,
        prefill-smoke maps to diagnose prefill, decode-loop maps to diagnose
        decode-loop-legacy, profile-generate maps to product profile generate,
        and validate-real maps to product validate device.
        """
    ).lstrip()
