from __future__ import annotations

import copy
import json
import textwrap
from pathlib import Path
from typing import Any

from .artifacts import (
    build_offline_artifact_manifests,
    ensure_output_dir,
    write_json,
    write_text,
)
from .config_emit import emit_parameter_config
from .python_ttnn import (
    build_codegen_config,
    render_python_ttnn_model,
)
from ..semantic.dump import graph_json_dict
from ..semantic.graph import LlamaModelGraph
from ..templates.diff import expand_final_templates, expand_layer_templates


PROGRAM_ARTIFACTS = (
    "model.py",
    "config.json",
    "semantic_graph.json",
    "execution_plan.json",
    "weights_manifest.json",
    "run_decode.py",
    "README.md",
)


def write_decode_program_bundle(
    *,
    graph: LlamaModelGraph,
    plan: dict[str, Any],
    template_config: dict[str, Any],
    model_path: str | Path,
    out_dir: str | Path,
) -> dict[str, Path]:
    root = ensure_output_dir(out_dir)
    paths = {name: root / name for name in PROGRAM_ARTIFACTS}
    parameter_config = emit_parameter_config(
        graph,
        recipe=template_config["dtype_recipe"],
        lm_head_split_count=int(template_config["lm_head_split_count"]),
    )
    weights_manifest = build_offline_artifact_manifests(
        model_path,
        graph,
        parameter_config,
    )["weights_manifest.json"]

    write_text(paths["model.py"], render_python_ttnn_model(plan))
    write_json(paths["config.json"], build_codegen_config(plan))
    write_json(paths["semantic_graph.json"], graph_json_dict(graph))
    write_json(paths["execution_plan.json"], copy.deepcopy(plan))
    write_json(paths["weights_manifest.json"], weights_manifest)
    write_text(paths["run_decode.py"], render_run_decode_py(plan))
    write_text(paths["README.md"], render_program_readme(plan))
    return paths


def render_run_decode_py(plan: dict[str, Any]) -> str:
    dry_run_payload = build_decode_dry_run_payload(plan)
    return f'''# Auto-generated by Buddy-TTNN Direct.
from __future__ import annotations

import argparse
import json


DRY_RUN_PAYLOAD = {json.dumps(dry_run_payload, indent=4)}


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Run or inspect a Buddy-TTNN Direct decode bundle."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the per-layer op sequence without executing TTNN.",
    )
    args = parser.parse_args(argv)
    if args.dry_run:
        print(json.dumps(DRY_RUN_PAYLOAD, indent=2))
        return 0

    raise SystemExit(
        "Full decode execution is not implemented in Phase 11. "
        "Use --dry-run to inspect the generated op sequence."
    )


if __name__ == "__main__":
    raise SystemExit(main())
'''


def build_decode_dry_run_payload(plan: dict[str, Any]) -> dict[str, Any]:
    layers = [
        {
            "layer_id": layer["layer_id"],
            "ops": expand_layer_templates(layer["templates"]),
        }
        for layer in plan["layers"]
    ]
    return {
        "schema_version": 1,
        "mode": plan["mode"],
        "model_name": plan["model_name"],
        "num_layers": len(layers),
        "batch_size": plan["batch_size"],
        "seq_len": plan["seq_len"],
        "max_cache_len": plan["max_cache_len"],
        "layers": layers,
        "final_ops": expand_final_templates(plan["final"]),
    }


def render_program_readme(plan: dict[str, Any]) -> str:
    return textwrap.dedent(
        f"""
        # Buddy-TTNN Direct Decode Program

        This directory contains a generated Buddy-TTNN Direct decode bundle.
        It wires together semantic import, template planning, Python TTNN
        codegen, and offline weight metadata.

        Model: `{plan["model_name"]}`
        Layers: `{len(plan["layers"])}`
        Mode: `{plan["mode"]}`

        Generated files:

        ```text
        model.py
        config.json
        semantic_graph.json
        execution_plan.json
        weights_manifest.json
        run_decode.py
        README.md
        ```

        Inspect the decode op sequence with:

        ```bash
        python run_decode.py --dry-run
        ```

        Full TTNN decode execution is intentionally not enabled in Phase 11.
        """
    ).lstrip()
