from __future__ import annotations

import copy
import json
import textwrap
from pathlib import Path
from typing import Any

from .artifacts import (
    ensure_output_dir,
    planned_artifact_paths,
    write_json,
    write_text,
)


def validate_execution_plan_for_codegen(plan: dict[str, Any]) -> None:
    errors: list[str] = []
    if plan.get("schema_version") != 1:
        errors.append("schema_version must be 1")
    if plan.get("mode") != "decode":
        errors.append("Phase 3 codegen only supports decode plans")
    layers = plan.get("layers")
    if not isinstance(layers, list) or not layers:
        errors.append("plan must contain a non-empty layers list")
    else:
        for expected_id, layer in enumerate(layers):
            if layer.get("layer_id") != expected_id:
                errors.append(
                    f"layer_id mismatch at index {expected_id}: "
                    f"{layer.get('layer_id')}"
                )
            templates = layer.get("templates")
            if not isinstance(templates, list) or not templates:
                errors.append(f"layer {expected_id} has no templates")
    final = plan.get("final")
    if not isinstance(final, list) or not final:
        errors.append("plan must contain a non-empty final list")

    if errors:
        raise ValueError(
            "invalid execution plan for Python TTNN codegen:\n- "
            + "\n- ".join(errors)
        )


def build_codegen_config(plan: dict[str, Any]) -> dict[str, Any]:
    validate_execution_plan_for_codegen(plan)
    return {
        "schema_version": 1,
        "model_name": plan["model_name"],
        "num_layers": len(plan["layers"]),
        "mode": plan["mode"],
        "batch_size": plan["batch_size"],
        "seq_len": plan["seq_len"],
        "max_cache_len": plan["max_cache_len"],
        "template_config": copy.deepcopy(plan["template_config"]),
        "layers": copy.deepcopy(plan["layers"]),
        "final": copy.deepcopy(plan["final"]),
    }


def render_python_ttnn_model(plan: dict[str, Any]) -> str:
    config = build_codegen_config(plan)
    model_class = "BuddyLlama31TTNN"
    num_layers = int(config["num_layers"])
    attention_template = _template_name(
        plan, "official_paged_attention_decode"
    )
    mlp_template = _template_name(plan, "official_gated_mlp_decode")
    lm_head_template = _template_name(plan, "official_split_lm_head")
    generation_template = _template_name(plan, "device_argmax_greedy")

    return (
        textwrap.dedent(
            f'''
            # Auto-generated by Buddy-TTNN Direct.
            from __future__ import annotations

            import json
            from types import SimpleNamespace

            import ttnn


            def _to_namespace(value):
                if isinstance(value, dict):
                    return SimpleNamespace(
                        **{{key: _to_namespace(item) for key, item in value.items()}}
                    )
                if isinstance(value, list):
                    return [_to_namespace(item) for item in value]
                return value


            def load_config(path):
                with open(path) as handle:
                    return _to_namespace(json.load(handle))


            class {model_class}:
                def __init__(self, device, parameters, config):
                    self.device = device
                    self.parameters = parameters
                    self.config = config

                def decode_step(self, token_ids, page_table, cache_position, kv_cache):
                    hidden = self.embed(token_ids)
                    for layer_id in range(self.config.num_layers):
                        hidden = self.decode_layer(
                            layer_id,
                            hidden,
                            page_table,
                            cache_position,
                            kv_cache,
                        )
                    hidden = self.final_norm(hidden)
                    token = self.lm_head_argmax(hidden)
                    return token, kv_cache

                def decode_layer(self, layer_id, hidden, page_table, cache_position, kv_cache):
                    residual = hidden
                    hidden = self.rmsnorm(hidden, layer_id, kind="attn")
                    hidden = self.attention_decode(
                        layer_id,
                        hidden,
                        page_table,
                        cache_position,
                        kv_cache,
                    )
                    hidden = ttnn.add(residual, hidden)
                    residual = hidden
                    hidden = self.rmsnorm(hidden, layer_id, kind="mlp")
                    hidden = self.mlp_decode(layer_id, hidden)
                    hidden = ttnn.add(residual, hidden)
                    return hidden

                def embed(self, token_ids):
                    # TODO: ttnn.embedding for token ids.
                    raise NotImplementedError(
                        "Embedding template is not implemented in Phase 3."
                    )

                def rmsnorm(self, hidden, layer_id, kind):
                    # TODO: ttnn.rms_norm using per-layer RMSNorm weights.
                    raise NotImplementedError(
                        "RMSNorm template is not implemented in Phase 3."
                    )

                def final_norm(self, hidden):
                    # TODO: final ttnn.rms_norm before LM-head.
                    raise NotImplementedError(
                        "Final RMSNorm template is not implemented in Phase 3."
                    )

                def attention_decode(
                    self,
                    layer_id,
                    hidden,
                    page_table,
                    cache_position,
                    kv_cache,
                ):
                    # Template: {attention_template}
                    # TODO: ttnn.linear packed QKV
                    # TODO: ttnn.experimental.nlp_create_qkv_heads_decode
                    # TODO: rotary embedding
                    # TODO: paged_update_cache
                    # TODO: paged_scaled_dot_product_attention_decode
                    # TODO: nlp_concat_heads_decode
                    # TODO: output projection
                    raise NotImplementedError(
                        "Attention template {attention_template} is a Phase 3 skeleton."
                    )

                def mlp_decode(self, layer_id, hidden):
                    # Template: {mlp_template}
                    # TODO: gate projection with ttnn.linear
                    # TODO: up projection with ttnn.linear
                    # TODO: fused silu + multiply
                    # TODO: down projection with ttnn.linear
                    raise NotImplementedError(
                        "MLP template {mlp_template} is a Phase 3 skeleton."
                    )

                def lm_head_argmax(self, hidden):
                    # Template: {lm_head_template} + {generation_template}
                    # TODO: split LM-head projection
                    # TODO: concat shard logits
                    # TODO: device greedy argmax
                    raise NotImplementedError(
                        "LM-head template {lm_head_template} is a Phase 3 skeleton."
                    )


            GENERATED_NUM_LAYERS = {num_layers}
            '''
        ).lstrip()
    )


def render_codegen_readme(plan: dict[str, Any]) -> str:
    config = build_codegen_config(plan)
    return textwrap.dedent(
        f"""
        # Buddy-TTNN Direct Generated Skeleton

        This directory was generated from a Buddy-TTNN Direct execution plan.
        The generated `model.py` is a Phase 3 TTNN skeleton: it defines the
        decode program structure and template method boundaries, but heavy TTNN
        template bodies intentionally raise `NotImplementedError`.

        Model: `{config["model_name"]}`
        Layers: `{config["num_layers"]}`
        Mode: `{config["mode"]}`
        Batch size: `{config["batch_size"]}`
        Decode sequence length: `{config["seq_len"]}`

        Expected files:

        ```text
        model.py
        config.json
        plan.json
        README.md
        ```

        Validate syntax with:

        ```bash
        python -m py_compile model.py
        ```
        """
    ).lstrip()


def write_python_ttnn_skeleton(
    plan: dict[str, Any], out_dir: str | Path
) -> dict[str, Path]:
    validate_execution_plan_for_codegen(plan)
    root = ensure_output_dir(out_dir)
    paths = planned_artifact_paths(root)
    write_text(paths["model.py"], render_python_ttnn_model(plan))
    write_json(paths["config.json"], build_codegen_config(plan))
    write_json(paths["plan.json"], copy.deepcopy(plan))
    write_text(paths["README.md"], render_codegen_readme(plan))
    return paths


def dry_run_report(plan: dict[str, Any], out_dir: str | Path) -> dict[str, Any]:
    config = build_codegen_config(plan)
    return {
        "dry_run": True,
        "model_name": config["model_name"],
        "num_layers": config["num_layers"],
        "out_dir": str(out_dir),
        "artifacts": sorted(planned_artifact_paths(out_dir)),
    }


def _template_name(plan: dict[str, Any], expected: str) -> str:
    for layer in plan.get("layers", []):
        for template in layer.get("templates", []):
            if template == expected:
                return expected
    for template in plan.get("final", []):
        if template == expected:
            return expected
    return expected
