# ===- deepseek_chat_run.py --------------------------------------------------
#
# Interactive DeepSeek-R1-Distill-Qwen-1.5B chat runner driving P150A via
# ``ttrt.runtime``.  Mirrors ``buddy-deepseek-r1-main.cpp`` (the f32 CPU
# reference) in flow and console output so results from the two backends are
# directly comparable.
#
# Prerequisites (see ``run_deepseek_p150_chat.sh``):
#   * ``deepseek_prefill_static.ttnn`` and ``deepseek_decode_static.ttnn`` built
#     from ``buddy-deepseek-r1-lower-ttir.py --static-cache --max-cache-len N``.
#   * ``chat_artifacts/{prefill,decode}/*`` generated by
#     ``deepseek_chat_prepare.py`` with a matching ``--max-cache-len``.
#
# ===---------------------------------------------------------------------------

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path

import numpy as np
import torch

_BOLD_YELLOW = "\033[33;1m"
_BOLD_GREEN = "\033[32;1m"
_BOLD_BLUE = "\033[34;1m"
_RESET = "\033[0m"


def _log(msg: str) -> None:
    print(f"{_BOLD_BLUE}[Log]{_RESET} {msg}")


def _iter_info(idx: int, tok: str, seconds: float) -> None:
    # Escape whitespace that would otherwise break the single-line iteration
    # print (e.g. token "\n\n" or ".\n"). The original token is preserved in
    # the final ``[Output]`` block below so nothing is lost.
    display = (
        tok.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    )
    print(
        f"{_BOLD_GREEN}[Iteration {idx}] {_RESET}"
        f"Token: {display} | Time: {seconds:.4f}s"
    )


def _ensure_ttrt():
    try:
        import ttrt  # noqa: F401
        from ttrt.common.api import API

        API.initialize_apis()
        import ttrt.runtime  # noqa: F401
        from ttrt.common.query import Query
        from ttrt.common.util import (
            Binary,
            FileManager,
            Logger,
            convert_input_layouts,
            convert_runtime_to_torch_tensor,
            create_tensor,
        )
    except ImportError as e:
        print(f"error: ttrt import failed: {e}", file=sys.stderr)
        raise SystemExit(1) from e
    return (
        Query,
        Binary,
        FileManager,
        Logger,
        convert_input_layouts,
        convert_runtime_to_torch_tensor,
        create_tensor,
    )


def _numpy_to_torch(arr: np.ndarray, stored_dtype: str, target: torch.dtype) -> torch.Tensor:
    if stored_dtype == "bfloat16":
        t = torch.from_numpy(arr.astype(np.uint16, copy=False)).view(torch.bfloat16)
    elif stored_dtype == "float16":
        t = torch.from_numpy(arr.astype(np.uint16, copy=False)).view(torch.float16)
    elif stored_dtype == "float32":
        t = torch.from_numpy(arr.astype(np.float32, copy=False))
    elif stored_dtype == "int64":
        t = torch.from_numpy(arr.astype(np.int64, copy=False))
    elif stored_dtype == "int32":
        t = torch.from_numpy(arr.astype(np.int32, copy=False))
    elif stored_dtype == "bool":
        t = torch.from_numpy(arr.astype(np.uint8, copy=False)).to(torch.bool)
    else:
        raise ValueError(f"unsupported stored_dtype {stored_dtype}")
    if t.dtype != target:
        t = t.to(target)
    return t


def _ttnn_dtype_to_torch(Binary, dt) -> torch.dtype:
    return Binary.Program.from_data_type(dt)


class PhaseCtx:
    """All host-side state needed to build one phase's input_tensors."""

    def __init__(self, artifacts_dir: Path, ttnn_path: Path, phase: str):
        self.phase = phase
        self.roles: list[dict] = json.loads(
            (artifacts_dir / phase / "slot_roles.json").read_text()
        )
        self.shapes: list[list[int]] = json.loads(
            (artifacts_dir / phase / "shapes.json").read_text()
        )
        self.dtypes: list[str] = json.loads(
            (artifacts_dir / phase / "dtypes.json").read_text()
        )
        self.weights: dict[str, np.ndarray] = {}
        wpath = artifacts_dir / phase / "weights.npz"
        if wpath.exists():
            self.weights = dict(np.load(wpath))
        self.inv_freq: np.ndarray | None = None
        ipath = artifacts_dir / phase / "inv_freq.npy"
        if ipath.exists():
            self.inv_freq = np.load(ipath)
        self.ttnn_path = ttnn_path


def _build_prefill_inputs(
    ctx: PhaseCtx,
    input_ids_np: np.ndarray,
    program_inputs,
    Binary,
) -> list[torch.Tensor]:
    tensors: list[torch.Tensor] = []
    assert len(program_inputs) == len(ctx.roles), (
        f"prefill: program expects {len(program_inputs)} inputs, "
        f"artifacts describe {len(ctx.roles)}"
    )
    for slot, role_entry in enumerate(ctx.roles):
        role = role_entry["role"]
        tdt = _ttnn_dtype_to_torch(
            Binary,
            program_inputs[slot]["desc"]["layout"]["memory_desc"]["data_type"],
        )
        stored_dtype = ctx.dtypes[slot]
        shp = role_entry["shape"]
        if role == "weight":
            arr = ctx.weights[f"w_{slot:04d}"]
            t = _numpy_to_torch(arr, stored_dtype, tdt)
        elif role == "input_ids":
            t = _numpy_to_torch(input_ids_np, "int64", tdt)
        elif role == "inv_freq":
            t = _numpy_to_torch(ctx.inv_freq, "float32", tdt)
        else:
            raise RuntimeError(f"prefill: unexpected role {role!r} at slot {slot}")
        if list(t.shape) != shp:
            t = t.reshape(shp)
        tensors.append(t)
    return tensors


def _build_decode_inputs(
    ctx: PhaseCtx,
    last_token: int,
    cache_pos: int,
    past_kv_host: dict[str, np.ndarray],
    program_inputs,
    Binary,
) -> list[torch.Tensor]:
    tensors: list[torch.Tensor] = []
    assert len(program_inputs) == len(ctx.roles), (
        f"decode: program expects {len(program_inputs)} inputs, "
        f"artifacts describe {len(ctx.roles)}"
    )
    input_ids_np = np.array([[last_token]], dtype=np.int64)
    cache_pos_np = np.array([cache_pos], dtype=np.int64)
    for slot, role_entry in enumerate(ctx.roles):
        role = role_entry["role"]
        tdt = _ttnn_dtype_to_torch(
            Binary,
            program_inputs[slot]["desc"]["layout"]["memory_desc"]["data_type"],
        )
        stored_dtype = ctx.dtypes[slot]
        shp = role_entry["shape"]
        if role == "weight":
            arr = ctx.weights[f"w_{slot:04d}"]
            t = _numpy_to_torch(arr, stored_dtype, tdt)
        elif role == "input_ids":
            t = _numpy_to_torch(input_ids_np, "int64", tdt)
        elif role == "cache_position":
            t = _numpy_to_torch(cache_pos_np, "int64", tdt)
        elif role.startswith("past_K_") or role.startswith("past_V_"):
            arr = past_kv_host[role]
            t = _numpy_to_torch(arr, "bfloat16", tdt)
        elif role == "inv_freq":
            t = _numpy_to_torch(ctx.inv_freq, "float32", tdt)
        else:
            raise RuntimeError(f"decode: unexpected role {role!r} at slot {slot}")
        if list(t.shape) != shp:
            t = t.reshape(shp)
        tensors.append(t)
    return tensors


def _shards_for_create_tensor(entry):
    if isinstance(entry, torch.Tensor):
        return [entry]
    return entry


def _precache_static_inputs(
    rt,
    Binary,
    device,
    fb_mesh_shape,
    bin_obj,
    prog_idx: int,
    ctx: "PhaseCtx",
    create_tensor,
) -> dict[int, object]:
    """Upload all static subgraph inputs (``weight`` + ``inv_freq``) to device
    once, mark them ``set_retain(True)`` so ``rt.submit`` does not deallocate
    them, and return ``{slot_idx: retained_device_tensor}``.

    This eliminates ~340 per-step ``create_tensor`` + ``to_layout`` calls that
    dominated the 375 ms/token host overhead previously measured.
    """
    program = _load_program(bin_obj, prog_idx)
    cached: dict[int, object] = {}
    for slot, role_entry in enumerate(ctx.roles):
        role = role_entry["role"]
        if role not in ("weight", "inv_freq"):
            continue
        tdt = _ttnn_dtype_to_torch(
            Binary,
            program.inputs[slot]["desc"]["layout"]["memory_desc"]["data_type"],
        )
        stored_dtype = ctx.dtypes[slot]
        shp = role_entry["shape"]
        if role == "weight":
            arr = ctx.weights[f"w_{slot:04d}"]
            t = _numpy_to_torch(arr, stored_dtype, tdt)
        else:
            t = _numpy_to_torch(ctx.inv_freq, "float32", tdt)
        if list(t.shape) != shp:
            t = t.reshape(shp)

        host_rt = create_tensor(_shards_for_create_tensor(t), fb_mesh_shape)
        layout = rt.get_layout(bin_obj.fbb, int(prog_idx), int(slot))
        dev_rt = rt.to_layout(host_rt, device, layout, True)
        dev_rt.set_retain(True)
        cached[slot] = dev_rt
    return cached


def _to_torch_host(ot, fb_mesh_shape, rt, convert_runtime_to_torch_tensor):
    host = rt.to_host(ot, untilize=True)
    mesh = fb_mesh_shape if len(host) > 1 else (1, 1)
    md = rt.create_multi_device_host_tensor_from_shards(host, {}, mesh)
    return convert_runtime_to_torch_tensor(md)


def _load_program(binary, program_index: int):
    program = binary.get_program(int(program_index))
    if program.is_private():
        raise RuntimeError("private program")
    return program


def _apply_chat_template(tokenizer, user_message: str, system_prompt: str | None) -> list[int]:
    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": user_message})
    try:
        ids = tokenizer.apply_chat_template(
            messages,
            add_generation_prompt=True,
            tokenize=True,
        )
    except Exception:
        prompt = (
            (f"<｜begin▁of▁sentence｜>" if system_prompt is None else "")
            + (f"<｜System｜>{system_prompt}" if system_prompt else "")
            + f"<｜User｜>{user_message}<｜Assistant｜>"
        )
        ids = tokenizer(prompt, add_special_tokens=False).input_ids
    if not isinstance(ids, list):
        ids = list(ids)
    return [int(x) for x in ids]


def _open_device(rt, binary, query):
    rt.set_compatible_device_runtime(binary.fbb)
    mesh_options = rt.MeshDeviceOptions()
    fb_mesh_shape = (1, 1)
    mesh_options.mesh_shape = fb_mesh_shape
    device = rt.open_mesh_device(mesh_options)
    return device, fb_mesh_shape


def _prefill_once(
    rt,
    Binary,
    convert_input_layouts,
    create_tensor,
    device,
    fb_mesh_shape,
    prefill_bin,
    prefill_prog_idx: int,
    prefill_ctx: PhaseCtx,
    input_ids_np: np.ndarray,
    cached_inputs: dict[int, object] | None = None,
):
    program = _load_program(prefill_bin, prefill_prog_idx)
    program.input_tensors.clear()
    program.output_tensors.clear()
    program.populate_outputs(
        lambda shape, dtype=None: torch.zeros(shape, dtype=dtype)
    )
    cached = cached_inputs or {}
    inputs_rt = [None] * len(program.inputs)
    for slot, role_entry in enumerate(prefill_ctx.roles):
        role = role_entry["role"]
        if slot in cached:
            inputs_rt[slot] = cached[slot]
            continue
        tdt = _ttnn_dtype_to_torch(
            Binary,
            program.inputs[slot]["desc"]["layout"]["memory_desc"]["data_type"],
        )
        shp = role_entry["shape"]
        if role == "input_ids":
            t = _numpy_to_torch(input_ids_np, "int64", tdt)
        else:
            raise RuntimeError(
                f"prefill: unexpected dynamic role {role!r} at slot {slot}"
            )
        if list(t.shape) != shp:
            t = t.reshape(shp)
        host_rt = create_tensor(_shards_for_create_tensor(t), fb_mesh_shape)
        layout = rt.get_layout(prefill_bin.fbb, int(prefill_prog_idx), int(slot))
        inputs_rt[slot] = rt.to_layout(host_rt, device, layout)
    start = time.perf_counter()
    runtime_outputs = rt.submit(
        device, prefill_bin.fbb, int(prefill_prog_idx), inputs_rt
    )
    rt.wait(runtime_outputs)
    elapsed = time.perf_counter() - start
    return runtime_outputs, elapsed


def _decode_once(
    rt,
    Binary,
    convert_input_layouts,
    create_tensor,
    device,
    fb_mesh_shape,
    decode_bin,
    decode_prog_idx: int,
    decode_ctx: PhaseCtx,
    last_token: int,
    cache_pos: int,
    past_kv_dev: dict[str, object],
    cached_inputs: dict[int, object] | None = None,
):
    program = _load_program(decode_bin, decode_prog_idx)
    program.input_tensors.clear()
    program.output_tensors.clear()
    program.populate_outputs(
        lambda shape, dtype=None: torch.zeros(shape, dtype=dtype)
    )
    cached = cached_inputs or {}
    input_ids_np = np.array([[last_token]], dtype=np.int64)
    cache_pos_np = np.array([cache_pos], dtype=np.int64)

    inputs_rt = [None] * len(program.inputs)
    for slot, role_entry in enumerate(decode_ctx.roles):
        role = role_entry["role"]
        if slot in cached:
            inputs_rt[slot] = cached[slot]
            continue
        if role.startswith("past_K_") or role.startswith("past_V_"):
            inputs_rt[slot] = past_kv_dev[role]
            continue
        # Only ``input_ids`` / ``cache_position`` still need a host round-trip;
        # both are tiny (<= 8 bytes on the wire).
        tdt = _ttnn_dtype_to_torch(
            Binary,
            program.inputs[slot]["desc"]["layout"]["memory_desc"]["data_type"],
        )
        shp = role_entry["shape"]
        if role == "input_ids":
            t = _numpy_to_torch(input_ids_np, "int64", tdt)
        elif role == "cache_position":
            t = _numpy_to_torch(cache_pos_np, "int64", tdt)
        else:
            raise RuntimeError(
                f"decode: unexpected dynamic role {role!r} at slot {slot}"
            )
        if list(t.shape) != shp:
            t = t.reshape(shp)
        host_rt = create_tensor(_shards_for_create_tensor(t), fb_mesh_shape)
        layout = rt.get_layout(decode_bin.fbb, int(decode_prog_idx), int(slot))
        inputs_rt[slot] = rt.to_layout(host_rt, device, layout)

    start = time.perf_counter()
    runtime_outputs = rt.submit(
        device, decode_bin.fbb, int(decode_prog_idx), inputs_rt
    )
    rt.wait(runtime_outputs)
    elapsed = time.perf_counter() - start
    return runtime_outputs, elapsed


def _extract_logits_and_kv(
    rt,
    convert_runtime_to_torch_tensor,
    runtime_outputs,
    fb_mesh_shape,
    logits_index: int,
    kv_role_map: list[str] | None,
):
    if logits_index < 0:
        logits_index = len(runtime_outputs) + logits_index
    logits_t = _to_torch_host(
        runtime_outputs[logits_index], fb_mesh_shape, rt, convert_runtime_to_torch_tensor
    )
    kv_host: dict[str, np.ndarray] = {}
    if kv_role_map is not None:
        kv_iter = 0
        for oi, ot in enumerate(runtime_outputs):
            if oi == logits_index:
                continue
            if kv_iter >= len(kv_role_map):
                break
            role = kv_role_map[kv_iter]
            tt = _to_torch_host(ot, fb_mesh_shape, rt, convert_runtime_to_torch_tensor)
            kv_host[role] = tt.view(torch.uint16).numpy().astype(np.uint16)
            kv_iter += 1
    for ot in runtime_outputs:
        rt.deallocate_tensor(ot, force=True)
    return logits_t, kv_host


def _extract_logits_and_kv_device(
    rt,
    convert_runtime_to_torch_tensor,
    runtime_outputs,
    fb_mesh_shape,
    device,
    target_bin,
    target_prog_idx: int,
    target_kv_input_slots: dict[str, int],
    logits_index: int,
    kv_role_map: list[str] | None,
):
    """Host-copy the logits but keep every KV tensor device-resident.

    Each KV output is passed through ``rt.to_layout`` using the next-phase
    input layout (decode's input slot layout), so the returned ``kv_dev`` dict
    can be fed straight back into the next ``rt.submit`` call without any
    host round-trip.
    """
    if logits_index < 0:
        logits_index = len(runtime_outputs) + logits_index
    logits_t = _to_torch_host(
        runtime_outputs[logits_index], fb_mesh_shape, rt, convert_runtime_to_torch_tensor
    )
    kv_dev: dict[str, object] = {}
    if kv_role_map is not None:
        kv_iter = 0
        for oi, ot in enumerate(runtime_outputs):
            if oi == logits_index:
                continue
            if kv_iter >= len(kv_role_map):
                break
            role = kv_role_map[kv_iter]
            target_slot = target_kv_input_slots[role]
            target_layout = rt.get_layout(
                target_bin.fbb, int(target_prog_idx), int(target_slot)
            )
            kv_dev[role] = rt.to_layout(ot, device, target_layout)
            kv_iter += 1
    # Logits already copied; safely force-free it. KV original output handles
    # are released via reference counting (``to_layout`` may alias or copy).
    for oi, ot in enumerate(runtime_outputs):
        if oi == logits_index:
            rt.deallocate_tensor(ot, force=True)
        else:
            rt.deallocate_tensor(ot)
    return logits_t, kv_dev


def main() -> int:
    (
        Query,
        Binary,
        FileManager,
        Logger,
        convert_input_layouts,
        convert_runtime_to_torch_tensor,
        create_tensor,
    ) = _ensure_ttrt()
    import ttrt.runtime  # noqa: F811

    p = argparse.ArgumentParser(
        description="Interactive DeepSeek-R1 chat runner on P150A (TTIR, bf16)."
    )
    p.add_argument("--prefill-ttnn", type=Path, required=True)
    p.add_argument("--decode-ttnn", type=Path, required=True)
    p.add_argument("--artifacts", type=Path, required=True)
    p.add_argument(
        "--model",
        type=str,
        default=os.environ.get(
            "LLAMA31_MODEL_PATH", "meta-llama/Llama-3.1-8B-Instruct"
        ),
        help="HF tokenizer path / id (trust_remote_code=True).",
    )
    p.add_argument("--program-index", type=int, default=0)
    p.add_argument("--max-cache-len", type=int, default=1024)
    # Llama-3.1-Instruct's generation_config lists eos_token_id=[128001, 128008,
    # 128009]; ``<|eot_id|>`` (128009) is the end-of-turn marker used by the
    # standard chat template.
    p.add_argument("--eos-token-id", type=int, default=128009)
    p.add_argument(
        "--system-prompt",
        type=str,
        default=None,
        help="Optional system prompt inserted into the chat template.",
    )
    p.add_argument("--ignore-system-desc", action="store_true")
    p.add_argument(
        "--max-new-tokens",
        type=int,
        default=0,
        help="Cap decode loop at this many tokens (0 = run until EOS or cache full).",
    )
    p.add_argument(
        "--ignore-eos",
        action="store_true",
        help="Keep generating until max-new-tokens / max-cache-len even after EOS; useful for perf benchmarks.",
    )
    args = p.parse_args()

    _log(f"prefill flatbuffer: {args.prefill_ttnn.resolve()}")
    _log(f"decode flatbuffer:  {args.decode_ttnn.resolve()}")
    _log(f"artifacts dir:      {args.artifacts.resolve()}")
    _log(f"max cache length:   {args.max_cache_len}")

    from transformers import AutoTokenizer

    tok_t0 = time.perf_counter()
    tokenizer = AutoTokenizer.from_pretrained(args.model, trust_remote_code=True)
    tok_t1 = time.perf_counter()
    _log(f"tokenizer ready in {(tok_t1 - tok_t0) * 1000.0:.1f}ms")

    logger = Logger("")
    file_manager = FileManager(logger)
    prefill_bin = Binary(logger, file_manager, str(args.prefill_ttnn.resolve()))
    decode_bin = Binary(logger, file_manager, str(args.decode_ttnn.resolve()))

    query = Query({"--quiet": True}, logger)
    query.preprocess()
    query.check_constraints()
    query.execute()
    query.postprocess()
    if query.test_result != "pass" or query.device_ids is None:
        print("error: ttrt query failed", file=sys.stderr)
        return 1
    if not args.ignore_system_desc:
        try:
            prefill_bin.check_system_desc(query, ignore=False)
            decode_bin.check_system_desc(query, ignore=False)
        except Exception as e:
            print(f"error: system desc: {e}", file=sys.stderr)
            return 1

    _log("loading prefill / decode artifacts...")
    prep_t0 = time.perf_counter()
    prefill_ctx = PhaseCtx(args.artifacts, args.prefill_ttnn, "prefill")
    decode_ctx = PhaseCtx(args.artifacts, args.decode_ttnn, "decode")
    prep_t1 = time.perf_counter()
    _log(
        f"artifacts loaded in {(prep_t1 - prep_t0):.2f}s "
        f"(prefill slots={len(prefill_ctx.roles)}, decode slots={len(decode_ctx.roles)})"
    )

    decode_output_kv_roles: list[str] = []
    decode_kv_input_slots: dict[str, int] = {}
    for slot, entry in enumerate(decode_ctx.roles):
        r = entry["role"]
        if r.startswith("past_K_") or r.startswith("past_V_"):
            decode_output_kv_roles.append(r)
            decode_kv_input_slots[r] = slot
    if not decode_output_kv_roles:
        print("error: decode slot_roles.json has no past_K_*/past_V_* roles", file=sys.stderr)
        return 1

    device, fb_mesh_shape = _open_device(ttrt.runtime, prefill_bin, query)
    prefill_cache: dict[int, object] = {}
    decode_cache: dict[int, object] = {}
    try:
        title = "Llama-3.1-8B-Instruct Inference Powered by Buddy Compiler (P150A TTIR)"
        print(f"{_BOLD_YELLOW}{title}{_RESET}")

        # Pre-upload all static weights / inv_freq to device once, retain them.
        # After this, every subsequent submit reuses the same device-resident
        # tensors instead of re-running 340+ to_layout() calls per step.
        cache_t0 = time.perf_counter()
        prefill_cache = _precache_static_inputs(
            ttrt.runtime,
            Binary,
            device,
            fb_mesh_shape,
            prefill_bin,
            args.program_index,
            prefill_ctx,
            create_tensor,
        )
        decode_cache = _precache_static_inputs(
            ttrt.runtime,
            Binary,
            device,
            fb_mesh_shape,
            decode_bin,
            args.program_index,
            decode_ctx,
            create_tensor,
        )
        cache_t1 = time.perf_counter()
        _log(
            f"uploaded & retained {len(prefill_cache)} prefill + "
            f"{len(decode_cache)} decode static tensors in "
            f"{(cache_t1 - cache_t0):.2f}s"
        )

        print("\nPlease send a message:")
        print(">>> ", end="", flush=True)
        user_msg = sys.stdin.readline().rstrip("\n")
        print()

        token_ids = _apply_chat_template(tokenizer, user_msg, args.system_prompt)
        token_cnt = len(token_ids)
        if token_cnt >= args.max_cache_len:
            print(
                f"error: prompt has {token_cnt} tokens, >= max_cache_len={args.max_cache_len}",
                file=sys.stderr,
            )
            return 1

        padded = np.full((1, args.max_cache_len), args.eos_token_id, dtype=np.int64)
        padded[0, :token_cnt] = np.array(token_ids, dtype=np.int64)
        _log(f"prompt tokens = {token_cnt}")

        prefill_outputs, prefill_elapsed = _prefill_once(
            ttrt.runtime,
            Binary,
            convert_input_layouts,
            create_tensor,
            device,
            fb_mesh_shape,
            prefill_bin,
            args.program_index,
            prefill_ctx,
            padded,
            cached_inputs=prefill_cache,
        )

        prefill_logits_t, prefill_kv_dev = _extract_logits_and_kv_device(
            ttrt.runtime,
            convert_runtime_to_torch_tensor,
            prefill_outputs,
            fb_mesh_shape,
            device,
            decode_bin,
            args.program_index,
            decode_kv_input_slots,
            logits_index=-1,
            kv_role_map=decode_output_kv_roles,
        )
        logits_np = prefill_logits_t.detach().float().cpu().numpy()
        if logits_np.ndim == 3:
            last_logits = logits_np[0, token_cnt - 1, :]
        else:
            last_logits = logits_np.reshape(-1)
        first_token = int(np.argmax(last_logits))
        first_str = tokenizer.decode([first_token], skip_special_tokens=False)
        _iter_info(0, first_str, prefill_elapsed)

        generated_tokens: list[int] = [first_token]
        past_kv_dev: dict[str, object] = prefill_kv_dev
        cache_pos = token_cnt
        decode_submit_total = 0.0
        decode_wall_total = 0.0
        decode_token_count = 0
        decode_step_submit_times: list[float] = []
        decode_step_wall_times: list[float] = []

        max_iters = args.max_cache_len - token_cnt
        if args.max_new_tokens > 0:
            max_iters = min(max_iters, args.max_new_tokens - 1)
        for i in range(1, max_iters + 1):
            iter_t0 = time.perf_counter()
            decode_outputs, dec_submit = _decode_once(
                ttrt.runtime,
                Binary,
                convert_input_layouts,
                create_tensor,
                device,
                fb_mesh_shape,
                decode_bin,
                args.program_index,
                decode_ctx,
                last_token=generated_tokens[-1],
                cache_pos=cache_pos,
                past_kv_dev=past_kv_dev,
                cached_inputs=decode_cache,
            )
            decode_logits_t, new_kv_dev = _extract_logits_and_kv_device(
                ttrt.runtime,
                convert_runtime_to_torch_tensor,
                decode_outputs,
                fb_mesh_shape,
                device,
                decode_bin,
                args.program_index,
                decode_kv_input_slots,
                logits_index=-1,
                kv_role_map=decode_output_kv_roles,
            )
            # Free last step's KV immediately - force=True ensures the
            # underlying DRAM bank is released back to the allocator rather
            # than deferred via refcount. On Llama-3.1-8B the KV takes ~128 MB
            # per layer and DRAM is already at 20+ GB (16 GB weights + 4 GB
            # KV), so any deferred release fragments DRAM within 2-3 steps.
            # The prefill_kv_dev / previous-step new_kv_dev handles are no
            # longer aliased with ``runtime_outputs`` (they went through
            # ``rt.to_layout``), so force=True is safe.
            for old_kv in past_kv_dev.values():
                try:
                    ttrt.runtime.deallocate_tensor(old_kv, force=True)
                except Exception:
                    pass
            past_kv_dev = new_kv_dev

            ll = decode_logits_t.detach().float().cpu().numpy().reshape(-1)
            next_token = int(np.argmax(ll))
            next_str = tokenizer.decode([next_token], skip_special_tokens=False)
            iter_elapsed = time.perf_counter() - iter_t0
            _iter_info(i, next_str, iter_elapsed)
            decode_submit_total += dec_submit
            decode_wall_total += iter_elapsed
            decode_step_submit_times.append(dec_submit)
            decode_step_wall_times.append(iter_elapsed)
            decode_token_count += 1
            if next_token == args.eos_token_id and not args.ignore_eos:
                break
            generated_tokens.append(next_token)
            cache_pos += 1

        prefill_seconds = prefill_elapsed
        prefill_tokens_per_sec = (
            float(args.max_cache_len) / prefill_seconds if prefill_seconds > 0 else 0.0
        )
        # Wall-clock tokens/s: what the user actually experiences (submit + KV
        # to_host + re-tensorize + layout conversion for the next step).
        decode_wall_tokens_per_sec = (
            float(decode_token_count) / decode_wall_total
            if decode_wall_total > 0
            else 0.0
        )
        # Submit-only tokens/s: what the device compute alone would give if
        # host overhead were zero.  Useful for comparing against a hypothetical
        # keep-KV-on-device implementation.
        decode_submit_tokens_per_sec = (
            float(decode_token_count) / decode_submit_total
            if decode_submit_total > 0
            else 0.0
        )
        total_time = prefill_seconds + decode_wall_total
        output_text = tokenizer.decode(generated_tokens, skip_special_tokens=False)

        # Steady-state excludes the first decode step whose ``rt.submit`` pays
        # the one-time JIT cost for every decode kernel (attention, softmax,
        # layernorm, matmul, ...).  Once JIT is warm each subsequent step is
        # bound by the host-side KV shuffle, not compute.
        steady_n = max(0, decode_token_count - 1)
        steady_wall = sum(decode_step_wall_times[1:]) if steady_n > 0 else 0.0
        steady_submit = sum(decode_step_submit_times[1:]) if steady_n > 0 else 0.0
        steady_wall_tps = float(steady_n) / steady_wall if steady_wall > 0 else 0.0
        steady_submit_tps = (
            float(steady_n) / steady_submit if steady_submit > 0 else 0.0
        )
        first_wall = decode_step_wall_times[0] if decode_step_wall_times else 0.0
        first_submit = decode_step_submit_times[0] if decode_step_submit_times else 0.0
        host_overhead_total = decode_wall_total - decode_submit_total
        host_overhead_per_tok_ms = (
            1000.0 * host_overhead_total / decode_token_count
            if decode_token_count > 0
            else 0.0
        )

        print(f"\n{_BOLD_YELLOW}[Total time]{_RESET} {total_time:.4f}s")
        print(
            f"{_BOLD_YELLOW}[Prefilling]{_RESET} {prefill_tokens_per_sec:.4f} tokens/s "
            f"(prefill_time={prefill_seconds:.4f}s, includes one-time JIT)"
        )
        print(
            f"{_BOLD_YELLOW}[Decoding wall]{_RESET} "
            f"{decode_wall_tokens_per_sec:.4f} tokens/s "
            f"({decode_token_count} tokens in {decode_wall_total:.4f}s, "
            f"first-step={first_wall:.4f}s)"
        )
        print(
            f"{_BOLD_YELLOW}[Decoding steady wall]{_RESET} "
            f"{steady_wall_tps:.4f} tokens/s "
            f"({steady_n} tokens in {steady_wall:.4f}s, "
            f"host-overhead avg={host_overhead_per_tok_ms:.1f}ms/tok)"
        )
        print(
            f"{_BOLD_YELLOW}[Decoding device-only]{_RESET} "
            f"{decode_submit_tokens_per_sec:.4f} tokens/s wall, "
            f"{steady_submit_tps:.4f} tokens/s steady "
            f"(rt.submit+wait only, first-step={first_submit:.4f}s)"
        )
        print(f"{_BOLD_YELLOW}[Input]{_RESET} {user_msg}")
        print(f"{_BOLD_YELLOW}[Output]{_RESET} {output_text}")
    finally:
        # Release latest (still-live) device KV tensors, then static caches.
        try:
            if "past_kv_dev" in locals():
                for t in past_kv_dev.values():
                    try:
                        ttrt.runtime.deallocate_tensor(t, force=True)
                    except Exception:
                        pass
        except Exception:
            pass
        for t in list(prefill_cache.values()) + list(decode_cache.values()):
            try:
                ttrt.runtime.deallocate_tensor(t, force=True)
            except Exception:
                pass
        ttrt.runtime.close_mesh_device(device)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
