from __future__ import annotations

_SOURCE = """\
# Auto-generated by Buddy-TTNN Direct.
from __future__ import annotations

import json
from types import SimpleNamespace

import ttnn
from models.llama_ttnn_direct.buddy_ttnn_direct.ttnn_compat.model_ops import (
    TTNNCompatOps,
    _tensor_memory_config,
    _tensor_shape,
)


def _to_namespace(value):
    if isinstance(value, dict):
        return SimpleNamespace(
            **{key: _to_namespace(item) for key, item in value.items()}
        )
    if isinstance(value, list):
        return [_to_namespace(item) for item in value]
    return value


def load_config(path):
    with open(path) as handle:
        return _to_namespace(json.load(handle))


def _optional_attr(obj, name, default=None):
    return getattr(obj, name, default)


def _template_choice(config, axis, default):
    template_config = _optional_attr(config, "template_config", None)
    autotune = _optional_attr(template_config, "autotune", None)
    if autotune is None:
        autotune = _optional_attr(config, "autotune", None)
    templates = _optional_attr(autotune, "templates", None)
    return _optional_attr(templates, axis, default)


"""


def render_preamble() -> str:
    return _SOURCE
