PROFILE_GENERATE_OFFICIAL_BASELINE_ID = "tt_metal_official_llama31_8b_b32"
PROFILE_GENERATE_OFFICIAL_TPS_PER_USER = 33.1
PROFILE_GENERATE_OFFICIAL_BATCH_SIZE = 32
PROFILE_GENERATE_MILESTONE_IDS = ("M0", "M1", "M2", "M3", "M4", "M5", "M6")
